apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 3
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - my-cluster-kafka
                topologyKey: "kubernetes.io/hostname"
    logging:
      loggers:
        log4j.logger.io.strimzi.kafka.oauth: DEBUG
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
        configuration:
          brokers:
            - broker: 0
              advertisedHost: 127.0.0.1
              advertisedPort: 7070
            - broker: 1
              advertisedHost: 127.0.0.1
              advertisedPort: 7071
            - broker: 2
              advertisedHost: 127.0.0.1
              advertisedPort: 7072
      - name: tls
        port: 9093
        tls: true
        type: internal
        authentication:
          accessTokenIsJwt: true
          checkAccessTokenType: false
          jwksEndpointUri: https://login.microsoftonline.com/1b5955bf-2426-4ced-8412-9fe81bb8bca4/discovery/v2.0/keys
          type: oauth
          validIssuerUri: https://sts.windows.net/1b5955bf-2426-4ced-8412-9fe81bb8bca4/
        configuration:
          brokers:
            - broker: 0
              advertisedHost: 127.0.0.1
              advertisedPort: 7080
            - broker: 1
              advertisedHost: 127.0.0.1
              advertisedPort: 7081
            - broker: 2
              advertisedHost: 127.0.0.1
              advertisedPort: 7082
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
